export const projects = [
  {
    title: 'Memories',
    description: "A full-stack MERN application to store pictures while adding descriptions and tags. React front-end using Node/Express server and MongoDB for data storage. Login capability and integration with Google OAuth.",
      image: '/images/memories.png',
      tags: ['Mongo', 'Express', 'React', 'Node', 'Responsive'],
    source: 'https://github.com/procy-dev/memories',
    visit: null,
    id: 0,
  },
  {
    title: 'E-Commerce',
    description:"A basic E-Commerce website using Commerce.js API as a means to store and manage transaction data. Usage of Material-UI for theme/styling.",
    image: '/images/ecommerce.jpg',
    tags: ['React', 'JavaScript', 'API', 'Responsive'],
    source: 'https://github.com/procy-dev/commerce-web-skeleton',
    visit: null,
    id: 1,
  },
  {
    title: 'GitHub Jobs',
    description: "A simple web app that makes use of the GitHub Jobs API using custom React Hooks. API fetch efficiency by pagination. Usage of Bootstrap for component styling.",
      image: '/images/gh_jobs.jpg',
      tags: ['React', 'API', 'Axios'],
    source: 'https://github.com/procy-dev/gh-jobs',
    visit: null,
    id: 2,
  },
  {
    title: 'Covid Tracker',
    description: "Use of Chart.js to plot basic metrics on the Covid-19 pandemic by ingesting API data from Mathdroid. Search by country made possible by mapping out available options from API.",
    image: '/images/covid_tracker.jpg',
    tags: ['React', 'API', 'Chart.js', 'Axios', 'Responsive'],
    source: 'https://github.com/procy-dev/covid-tracker',
    visit: null,
    id: 3,
  },
  {
    title: 'Landing Page',
    description: "A basic landing page that could be catered towards buisnesses that are client facing. Theme-UI used for styling.",
    image: '/images/startup.jpg',
    tags: ['React', 'Next.js', 'Responsive'],
    source: 'https://github.com/procy-dev/landing-page',
    visit: null,
    id: 4,
  },
  {
    title: 'More on the way!',
    description: "As tech evolves, so does my list of projects! Anytime I need to learn something new or reinforce current skills, the best way for me is to start a new project! Stay tuned for more!",
    image: '/images/dots.png',
    tags: [],
    source: null,
    visit: null,
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2003, text: 'Built my first computer', },
  { year: 2007, text: 'Started programming in Java and DarkBASIC', },
  { year: 2011, text: 'Attended NAU pursuing a BS in Computer Science', },
  { year: 2013, text: 'Attained job as Lab Leader at NAU', },
  { year: 2015, text: 'Graduated with a BS in Computer Science', },
  { year: 2016, text: 'First job as Front-End developer', },
  { year: 2018, text: 'Promoted to Full-Stack Engineer', },
  { year: 2021, text: 'Survived a Pandemic!!!', },
];